services:
  redis:
    image: ${REDIS_IMAGE}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  toxiproxy:
    image: "shopify/toxiproxy"
    ports:
      - "8474:8474"
      - "22222:22222"
