services:
  redis:
    image: 'redis:6'
    command: --save "" --appendonly no
    ports:
      - "6379:6379"
  toxiproxy:
    image: 'shopify/toxiproxy'
    ports:
      - "8474:8474"
      - "22222:22222"
