name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    env:
      CI: true
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        kernel: [6.5.0-1025-azure]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential linux-headers-$(uname -r) wget unzip libelf-dev

      - name: Download kernel sources
        run: wget https://cl.archive.ubuntu.com/ubuntu/pool/main/l/linux-azure-6.5/linux-azure-6.5_6.5.0.orig.tar.gz && tar xvzf linux-azure-6.5_6.5.0.orig.tar.gz

      - name: Configure kernel sources
        run: |
          cp /boot/config-$(uname -r) linux-6.5/.config
          yes "" | make -C linux-6.5 oldconfig
          make -C linux-6.5 modules_prepare

      - name: Install knetstat
        run: |
          wget https://github.com/veithen/knetstat/archive/refs/heads/master.zip
          unzip master.zip
          cd knetstat-master
          make clean
          make

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install redis-cli
        run: sudo apt-get install redis-tools


      - name: Install dependencies
        run: npm install

      - name: Setup Standalone Tests
        run: make test-standalone-setup

      - name: Run Standalone tests
        run: make test-standalone

      - name: Teardown Standalone Tests
        run: make test-standalone-teardown

      - name: Setup Clustered Tests
        run: make test-cluster-setup

      - name: Check Redis Cluster
        run: timeout 60 bash <<< "until redis-cli -c -p 16371 cluster info | grep 'cluster_state:ok'; do sleep 1; done"

      - name: Run Clustered tests
        run: make test-cluster

      - name: Teardown Clustered Tests
        run: make test-cluster-teardown
