name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    env:
      CI: true
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        kernel: [6.5]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential linux-headers-$(uname -r) wget unzip libelf-dev

      - name: Download kernel sources
        run: curl https://cdn.kernel.org/pub/linux/kernel/$(echo ${{ matrix.kernel }} | sed -E 's/([^.]+)[.].*/v\1.x/')/linux-${{ matrix.kernel }}.tar.xz | tar xJ

      - name: Configure kernel sources
        run: |
          cp /boot/config-$(uname -r) linux-${{ matrix.kernel }}/.config
          yes "" | make -C linux-${{ matrix.kernel }} oldconfig
          make -C linux-${{ matrix.kernel }} modules_prepare

      - name: Install knetstat
        run: |
          wget https://github.com/veithen/knetstat/archive/refs/heads/master.zip
          unzip master.zip
          cd knetstat-master
          make KSRC=linux-${{ matrix.kernel }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install redis-cli
        run: sudo apt-get install redis-tools


      - name: Install dependencies
        run: npm install

      - name: Setup Standalone Tests
        run: make test-standalone-setup

      - name: Run Standalone tests
        run: make test-standalone

      - name: Teardown Standalone Tests
        run: make test-standalone-teardown

      - name: Setup Clustered Tests
        run: make test-cluster-setup

      - name: Check Redis Cluster
        run: timeout 60 bash <<< "until redis-cli -c -p 16371 cluster info | grep 'cluster_state:ok'; do sleep 1; done"

      - name: Run Clustered tests
        run: make test-cluster

      - name: Teardown Clustered Tests
        run: make test-cluster-teardown
